FROM maven:3.9.11-eclipse-temurin-21 AS builder
WORKDIR /app

COPY ../pom.xml ./
COPY ../mvnw ./
COPY ../.mvn .mvn
RUN chmod +x mvnw
RUN ./mvnw -q -DskipTests dependency:go-offline

COPY ../src src
RUN ./mvnw -q -DskipTests clean package

FROM eclipse-temurin:21-jre
WORKDIR /opt/app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/opt/app/app.jar"]
